# https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#exporting-an-environment-file-across-platforms
# File created using:
#
# conda env export --from-history
#
# with otter-grader manually added. Versions were manually updated in Fall 2024 for Practical Data Science.
name: pds
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip=24.2
  - matplotlib==3.9.2
  - matplotlib-inline==0.1.6
  - numpy==1.26.0
  - notebook==7.2.1
  - pandas==2.1.0
  - pydantic==2.8.2
  - PyYAML==6.0.1
  - requests==2.32.3
  - requests-oauthlib==2.0.0
  - tqdm==4.62.3
  - urllib3==1.26.7
  - scikit-learn==1.5.1
  - seaborn==0.13.2
  - beautifulsoup4==4.12.3
  - statsmodels==0.13.5
  - plotly==5.23.0
  - jupyterlab==4.2.4
  - jupyterlab_server==2.27.3
  - jupyterlab_widgets==3.0.13
  - nbclassic==1.1.0
  - ipywidgets==8.1.5
  - nbconvert==7.16.4
  - docopt==0.6.2
  - pytest-xdist==3.3.1
  - SQLAlchemy==2.0.21
  - pyOpenSSL==24.2.1
  - pip:
    - otter-grader==3.1.4